### PR TITLE
Create uname.md

### PR DESCRIPTION
**Pull request by cyb3rbary0n**

### CODE REVIEW

**Comment by cyb3rbary0n** [comment]
Do let me know if any changes required.

**Comment by cyb3rbary0n** [comment]
Do let me know if any changes required.

**Comment by cyb3rbary0n** [comment]
You've merged all other PRs except mine. May I ask why???

**Comment by AbhinavXT** [comment]
@cyb3rbary0n Add the description for the uname command. Here is the [link for description](https://linuxize.com/post/uname-command-in-linux/)

**Comment by AbhinavXT** [comment]
Also add it to the commands.md file.

**Review by cyb3rbary0n — COMMENTED** [review]
Added description.

**Pull request merged**
